# Makefile for the ltckpt pass
ROOT=../../..
CXXFLAGS+=-std=c++11
include $(ROOT)/Makefile.inc
PASSNAME := recovery
OBJS := StaticRecoveryPass.o

INCLUDES = -I../include

include $(ROOT)/llvm/passes/Makefile.inc
